export const SET_SELECTED_COUNTRY = "SET_SELECTED_COUNTRY"
export const SET_COUNTRIES = "SET_COUNTRIES"
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT"
export const SET_SHOWING_LIST = "SET_SHOWING_LIST"
